src/authentication/urls.py
from django.urls import path, reverse_lazy

from authentication.views import CustomerLoginView, AuthCheckView, CustomerLogoutView, RegistrationView, activateView, \
    UserExists, ApiLoginView, PassWordResetView, AdminPassWordResetView, Profile

app_name = 'authentication'
urlpatterns = [
    path('sign-in/', CustomerLoginView.as_view(), name='login'),
    path('api/check-auth/', AuthCheckView.as_view(), name='auth_check'),
    path('logout/', CustomerLogoutView.as_view(), name='logout'),
    path('create-account/', RegistrationView.as_view(), name='register'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activateView,
         name='activate'),
    path('user/profile/', Profile.as_view(), name="user_profile"),
    path('user_exists/', UserExists.as_view(), name='user_exists'),

    path("api/api_login/", ApiLoginView.as_view(), name="api_login"),

    path("password_reset/", PassWordResetView.as_view(), name="password_reset"),
    path("admin_password_reset/", AdminPassWordResetView.as_view(), name="admin_password_reset"),

]

src/customer/urls.py
from django.urls import path, include

from customer.views import DashboardView, RequestsView, RequestDetailsView, RequestReviewView, RequestsHistoryView, \
    RequestHisoryDetailsView, OrdersView, OrdersHistoryView, OrdersHistoryDetailsView

from customer.api_views import CustomerRequestView, CustomerOrderView, RequestHistoryApiView, RequestReviewApiView, \
    RequestCancelView

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'api/customer-request', CustomerRequestView)
router.register(r'api/customer-order', CustomerOrderView)
router.register(r'api/customer-request-history', RequestHistoryApiView)
router.register(r'api/customer-request-review', RequestReviewApiView)

app_name = 'customer'

urlpatterns = [
    path('profile/', DashboardView.as_view(), name="customer_dashboard"),
    path('requests/', RequestsView.as_view(), name="customer_requests"),
    path('request-details/<str:order_id>', RequestDetailsView.as_view(), name="customer_request_details"),
    path('request/<int:request_id>/review', RequestReviewView.as_view(), name="request.review"),
    path('requests-history/<str:order_id>', RequestsHistoryView.as_view(), name="customer_requests_history"),
    path('request-history-details/<str:id>', RequestHisoryDetailsView.as_view(),
         name="customer_request_history_details"),

    path('orders/', OrdersView.as_view(), name='customer_orders'),
    path('order-history/<str:order_id>', OrdersHistoryView.as_view(), name='order_history'),
    path('order-history-details/<int:pk>', OrdersHistoryDetailsView.as_view(), name='order_history_details')
]

# api urls
urlpatterns += [
    path('', include(router.urls)),
    path('api/requests-cancel/<int:pk>', RequestCancelView.as_view())
]

src/page/urls.py
from django.urls import path

from page.views import page

urlpatterns = [
    path('<str:slug>/', page)
]

src/product/urls.py
from django.urls import path, include

from product.apis.product import AttributeList, ClassificationList, AttributeByClassification, PartApiView, \
    HomePageView, PartView, PartDetailsApiView, WizardView, AddPartSupplierView, DeletePartSupplierView, \
    PartDetailsByIdView
from product.apis.supplier import PartSupplierView
from product.apis.supplier import SupplierView

app_name = 'product'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('part/<slug:slug>/', PartView.as_view(), name="part.details"),
    path('part/supplier/<int:id>/', PartSupplierView.as_view(), name="part.supplier"),
    # TODO:form wizard
    path('wizard/<slug:slug>/', WizardView.as_view(), name="wizard"),
    path('add/part-supplier/', AddPartSupplierView.as_view(), name='add.part.supplier'),
    path('delete/part-supplier/<int:id>', DeletePartSupplierView.as_view(), name='delete.part.supplier')
]

# url for api
urlpatterns += [
    path('api/', include([
        path('attribute/', AttributeList.as_view()),
        path('classification/', ClassificationList.as_view()),
        path('attribute/<int:id>', AttributeByClassification.as_view()),
        path('part/', PartApiView.as_view()),
        path('part-update/<int:id>/', PartApiView.as_view()),
        path('part/<slug:slug>', PartDetailsApiView.as_view()),
        path('part/supplier/', SupplierView.as_view()),
        path('part-details/<str:id>/', PartDetailsByIdView.as_view())
    ]))
]

src/supplier/urls.py
from django.urls import path, include
from supplier import views
from supplier.views import ModeratorRequestReviewList
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
# Assign unique basenames to prevent conflicts
router.register("api/supplier-requests", views.RequestReviewApiView, basename='supplier_requests')
router.register("api/moderator-requests", views.ModeratorRequestApiView, basename='moderator_requests')

app_name = "supplier"

urlpatterns = [
    path("requests", views.SupplierRequestView.as_view(), name="supplier_requests"),
    path('moderator-requests/', views.ModeratorRequestView.as_view(), name='moderator_request'),
    path('moderator-request/<int:request_id>/review', ModeratorRequestReviewList.as_view(),
         name='moderator.request.review'),
    path('request-details/<str:order_id>', views.SupplierRequestDetailsView.as_view(), name="supplier_request_details"),
    path('moderator/request-details/<str:order_id>', views.ModeratorRequestDetailsView.as_view(),
         name="moderator_request_details"),

    path('', include(router.urls))
]

src/triple_choice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from triple_choice import settings
from django.contrib.auth import views as auth_views

admin.site.site_header = settings.APP_SITE_HEADER
admin.site.site_title = settings.APP_SITE_TITLE
admin.site.index_title = settings.APP_INDEX_TITLE

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('super-admin/', admin.site.urls),
    path('', include("product.urls")),
    path('', include("order.urls")),
    path('', include("authentication.urls")),
    path('', include("page.urls")),
    path('user/', include("customer.urls")),
    path('supplier/', include("supplier.urls")),
    # path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # path("v1/payment_intents", include("djstripe.urls", namespace="djstripe")),

    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="frontend/authentication/password_reset_done.html"),
         name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="frontend/authentication/password_reset_confirm.html", ),
         name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="frontend/authentication/password_reset_complete.html"),
         name="password_reset_complete")

]
urlpatterns + static(settings.STATIC_URL)
# urlpatterns += + static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/dashboard/include/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>&copy; 2017 - 2018 TripleChoice. All Rights Reserved</span>
        </div>
    </div>
</footer>

src/templates/dashboard/include/header.html
{% load static %}
<style>
    .dropdown-menu-right {
        left: auto !important;
    }
</style>
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!--    <ul class="navbar-nav ">
            <a target="_blank" class=" btn btn-primary text-light btn-sm nav-link " href="{% url 'product:home' %}">Website</a>
        </ul>-->

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <div class="topbar-divider d-none d-sm-block"></div>
        <!-- Nav Item - User Information -->

        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="" id="userDropdown"
               role="button"
               data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuButtonProfile">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% firstof user.first_name user.email %}</span>
{#                <img class="img-profile rounded-circle"#}
{#                         src="{% static '/assets/user_avater.png' %}">#}
                {% if user.userprofile.file %}
                    <img class="img-profile rounded-circle" src="{{ user.userprofile.file.url }}">
                {% else %}
                    <img class="img-profile rounded-circle"
                         src="{% static '/assets/user_avater.png' %}">
                {% endif %}
            </a>
            <!--            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                            <img class="img-profile rounded-circle" src="img/undraw_profile.svg">
                                        </a>-->
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in " aria-labelledby="userDropdown"
                 aria-labelledby="dropdownMenuButtonProfile">

                <a class="dropdown-item" href="{% url 'authentication:user_profile' %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <div class="dropdown-divider"></div>

                <a class="dropdown-item" href="{% url 'authentication:logout' %}" data-toggle="modal"
                   data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>

src/templates/dashboard/include/sidebar.html
{% load static %}
{% load auth_extras %}
<style>
    .link-clicked {
        background: #FFF;
        color: #000000 !important;
    }
    .sidebar-dark .sidebar-brand{
        background : #fff;
    }
</style>
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a target="_blank" class="sidebar-brand d-flex align-items-center justify-content-center"
       href="{% url 'product:home' %}">
<!--        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-tools"></i>
        </div>-->
        <div class="sidebar-brand-text" style="text-transform: none">
            <img class="img-fluid" src="{% static '/assets/main.png' %}" alt="">
        </div>
    </a>

    <!-- Divider -->
<!--    <hr class="sidebar-divider my-0">-->
    <!-- Nav Item - Orders -->
    {% with request.resolver_match.url_name as url_name %}
        {% if request.user|is_in_group:"customer" and request.user|has_permission:"order.view_request" %}
            <li class="nav-item">
                <a class="nav-link {% if url_name == 'customer_requests' %} link-clicked {% endif %}"
                   href="{% url 'customer:customer_requests' %}?template=request-detaials">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Request</span></a>
            </li>

        {% endif %}
        {% if request.user|is_in_group:"supplier" and request.user|has_permission:"order.view_request" %}
            <li class="nav-item">
                <a class="nav-link {% if url_name == 'supplier_requests' %} link-clicked {% endif %}"
                   href="{% url 'supplier:supplier_requests' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Supplier Requests</span></a>
            </li>

        {% endif %}

        {% if request.user|is_in_group:"moderator" %}
            <li class="nav-item">
                <a class="nav-link {% if url_name == 'moderator_request' %} link-clicked {% endif %}"
                   href="{% url 'supplier:moderator_request' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Moderator Requests</span></a>
            </li>
        {% endif %}

        {% if request.user|is_in_group:"customer" and request.user|has_permission:"order.view_orderinfo" %}
            <li class="nav-item">
                <a class="nav-link {% if url_name == 'customer_orders' %} link-clicked {% endif %}"
                   href="{% url 'customer:customer_orders' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Order</span></a>
            </li>
        {% endif %}
    {% endwith %}


    <!-- Nav Item - Pages Collapse Menu -->
    <!--    <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
               aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-folder"></i>
                <span>Pages</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Login Screens:</h6>
                    <a class="collapse-item" href="login.html">Login</a>
                    <a class="collapse-item" href="register.html">Register</a>
                    <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                    <div class="collapse-divider"></div>
                    <h6 class="collapse-header">Other Pages:</h6>
                    <a class="collapse-item" href="404.html">404 Page</a>
                    <a class="collapse-item" href="blank.html">Blank Page</a>
                </div>
            </div>
        </li>-->

</ul>