src/authentication/urls.py
from django.urls import path, reverse_lazy

from authentication.views import CustomerLoginView, AuthCheckView, CustomerLogoutView, RegistrationView, activateView, \
    UserExists, ApiLoginView, PassWordResetView, AdminPassWordResetView, Profile

app_name = 'authentication'
urlpatterns = [
    path('sign-in/', CustomerLoginView.as_view(), name='login'),
    path('api/check-auth/', AuthCheckView.as_view(), name='auth_check'),
    path('logout/', CustomerLogoutView.as_view(), name='logout'),
    path('create-account/', RegistrationView.as_view(), name='register'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activateView,
         name='activate'),
    path('user/profile/', Profile.as_view(), name="user_profile"),
    path('user_exists/', UserExists.as_view(), name='user_exists'),

    path("api/api_login/", ApiLoginView.as_view(), name="api_login"),

    path("password_reset/", PassWordResetView.as_view(), name="password_reset"),
    path("admin_password_reset/", AdminPassWordResetView.as_view(), name="admin_password_reset"),

]

src/page/urls.py
from django.urls import path

from page.views import page

urlpatterns = [
    path('<str:slug>/', page)
]

src/triple_choice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from triple_choice import settings
from django.contrib.auth import views as auth_views

admin.site.site_header = settings.APP_SITE_HEADER
admin.site.site_title = settings.APP_SITE_TITLE
admin.site.index_title = settings.APP_INDEX_TITLE

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('super-admin/', admin.site.urls),
    path('', include("product.urls")),
    path('', include("order.urls")),
    path('', include("authentication.urls")),
    path('', include("page.urls")),
    path('user/', include("customer.urls")),
    path('supplier/', include("supplier.urls")),
    # path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # path("v1/payment_intents", include("djstripe.urls", namespace="djstripe")),

    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="frontend/authentication/password_reset_done.html"),
         name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="frontend/authentication/password_reset_confirm.html", ),
         name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="frontend/authentication/password_reset_complete.html"),
         name="password_reset_complete")

]
urlpatterns + static(settings.STATIC_URL)
# urlpatterns += + static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/authentication/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

from triple_choice.db.mixins import AuthorMixin, TimeStampMixin


class UserManager(BaseUserManager):
    def create_superuser(self, username, email, password, company_name, phone):
        user = self.model(
            email=email,
            password=password,
            username=username,
            company_name=company_name,
            phone=phone
        )
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        userprofile = UserProfile.objects.create(user=user)
        userprofile.save()
        return user


class User(AbstractUser):
    email = models.EmailField(max_length=255, unique=True)
    company_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=25)
    REQUIRED_FIELDS = ['email', 'company_name', 'phone']

    objects = UserManager()

    def __str__(self):
        return self.username


class UserProfile(models.Model):
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    file = models.ImageField(upload_to='media', blank=True, null=True)

    billing_street = models.CharField(max_length=255, blank=True, null=True)
    billing_building = models.CharField(max_length=255, blank=True, null=True)
    billing_state = models.CharField(max_length=50, blank=True, null=True)
    billing_city = models.CharField(max_length=250, blank=True, null=True)
    billing_zip_code = models.CharField(max_length=50, blank=True, null=True)

    shipping_street = models.CharField(max_length=255, blank=True, null=True)
    shipping_building = models.CharField(max_length=255, blank=True, null=True)
    shipping_state = models.CharField(max_length=50, blank=True, null=True)
    shipping_city = models.CharField(max_length=250, blank=True, null=True)
    shipping_zip_code = models.CharField(max_length=50, blank=True, null=True)

src/authentication/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from authentication.models import User, UserProfile
from django.contrib.auth.models import Group


class LoginForm(AuthenticationForm):
    error_css_class = 'is-invalid'

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control form-control-user', 'placeholder': 'Enter your email'}
    ), required=True)
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-user', 'placeholder': 'Enter your password'}
    ), required=True)


class RegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={
            'minlength': 8
        }
    ))
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput(
            attrs={
                'minlength': 8
            }
        ))

    email = forms.EmailField(required=True, max_length=100, widget=forms.TextInput())
    first_name = forms.CharField(required=False, max_length=100, widget=forms.TextInput())
    last_name = forms.CharField(required=False, max_length=100, widget=forms.TextInput())
    company_name = forms.CharField(max_length=100, widget=forms.TextInput())
    phone = forms.CharField(max_length=100, widget=forms.TextInput())

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', "first_name", "last_name", "company_name", "phone")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        group = Group.objects.filter(name='customer').first()
        user.is_active = False
        if commit:
            user.save()
        group.user_set.add(user)
        return user


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ['company_name', 'phone', 'first_name', 'last_name']


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = UserProfile
        fields = '__all__'

src/authentication/views.py
from django.contrib import auth
from django.views import View
from django.shortcuts import resolve_url, redirect, render
from django.urls import reverse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from authentication.forms import LoginForm, RegistrationForm, UserForm, UserProfileForm
from authentication.serilizers.user_serializer import UserSerializer
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import login
from authentication.models import User, UserProfile
from authentication.token import account_activation_token
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from authentication.email import send_activation_email, send_password_reset_email

from django.contrib.auth.forms import PasswordResetForm


class CustomerLoginView(auth_views.LoginView):

    def get(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated and (not user.is_superuser):
            return redirect('customer:customer_dashboard')

        return render(request, 'frontend/authentication/login.html', {"form": LoginForm})

    def post(self, request, *args, **kwargs):
        form = LoginForm(data=request.POST)
        try:
            if request.POST.get('username') == "":
                messages.error(request, message='Email field is required', extra_tags='error')
                return render(request, 'frontend/authentication/login.html', {'form': form})

            if request.POST.get('password') == "":
                messages.error(request, message='Password field is required', extra_tags='error')
                return render(request, 'frontend/authentication/login.html', {'form': form})
            user = User.objects.get(email=request.POST.get('username'))
            if not user.is_active:
                messages.error(request,
                               message='Your account is not active. Please active you account from given email, Otherwise contact with admin',
                               extra_tags='error')
                return redirect('authentication:login')

            if user.check_password(request.POST.get('password')):
                login(request, user)
                url = self.request.GET.get('url')

                if url is not None:
                    if url.split('/')[1] == 'part':
                        return redirect(reverse('product:part.details', args=[url.split('/')[2]]))

                messages.success(request, 'Login successfully', extra_tags='success')
                return redirect('customer:customer_dashboard')
            messages.error(request, message='Credential not match', extra_tags='error')
            return render(request, 'frontend/authentication/login.html', {'form': form})
        except:
            messages.error(request, message='User not found', extra_tags='error')
            return redirect('authentication:login')

    def get_success_url(self):
        url = self.request.GET.get('url')
        if url is not None:
            if url.split('/')[1] == 'part':
                return resolve_url(reverse('product:part.details', args=[url.split('/')[2]]))
        # TODO::"set user url"
        return resolve_url(reverse('customer:customer_dashboard'))

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except Exception:
            raise None


class AuthCheckView(APIView):
    def get(self, request):
        try:
            user = auth.get_user(request)
            serializer = UserSerializer(user)
            return Response(serializer.data)
        except Exception:
            raise Exception


class CustomerLogoutView(APIView):
    def get(self, request):
        logout(request)
        return redirect('/')


class Profile(View):
    def get(self, request):
        if request.user.is_authenticated:
            user_form = UserForm(instance=request.user)
            user_profile_form = UserProfileForm(instance=request.user.userprofile)
            profile = UserProfile.objects.get(user=request.user)
            context = {
                'user_form': user_form,
                'user_profile_form': user_profile_form,
                'profile': profile
            }
            return render(request, 'frontend/authentication/profile.html', context)
        return redirect('authentication:login')

    def post(self, request):
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile successfully updated', extra_tags='success')
            return redirect('authentication:user_profile')


class RegistrationView(View):
    def get(self, request):
        user = request.user
        if user.is_authenticated and (not user.is_superuser):
            return redirect('/user')

        form = RegistrationForm()
        return render(request, 'frontend/authentication/registration.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile.objects.create(user=user)
            user_profile.save()
            send_activation_email(request, user)
            messages.success(request, 'We sent an email to activate your account ', extra_tags='success')
            return redirect('authentication:login')

        return render(request, 'frontend/authentication/registration.html', {'form': form})


def activateView(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


class UserExists(APIView):
    def post(self, request):
        username = request.data['username']
        password = request.data['password']
        user = User.objects.filter(email=username).first()
        if not user:
            return Response({"success": "success"}, status=status.HTTP_200_OK)
        user = user.check_password(password)
        if user:
            return Response({"success": "success"}, status=status.HTTP_200_OK)
        return Response({"error": "error"}, status=status.HTTP_400_BAD_REQUEST)


class ApiLoginView(APIView):
    def post(self, request, *args, **kwargs):
        email = request.data['email']
        password = request.data['password']
        user = User.objects.filter(email=email).first()
        if user is not None:
            if user.check_password(password):
                login(request, user)
                return Response({"is_logged_in": "logged_in"})
            else:
                return Response({"is_logged_in": "not_logged_in"})
        return Response({"is_logged_in": "no_user_found"})


class PassWordResetView(View):
    def get(self, request, *args, **kwargs):
        form = PasswordResetForm()

        return render(request, "frontend/authentication/password_reset.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']

        user = User.objects.filter(email=email).first()
        if user:
            send_password_reset_email(request, user)
            return redirect("password_reset_done")
        messages.error(request, message='User does not exist', extra_tags='error')
        return render(request, "frontend/authentication/password_reset.html", {"form": form})


class AdminPassWordResetView(View):
    def get(self, request, *args, **kwargs):
        form = PasswordResetForm()

        return render(request, "frontend/authentication/admin_password_reset.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']

        user = User.objects.filter(email=email).first()
        if user:
            if user.is_superuser:
                send_password_reset_email(request, user)
                return redirect("password_reset_done")
        messages.error(request, message='User does not exist or user is not super User', extra_tags='error')
        return render(request, "frontend/authentication/admin_password_reset.html", {"form": form})

src/authentication/templates/frontend/authentication/admin_login_page.html
{% extends 'frontend/base.html' %}

{% block title %} Admin Login {% endblock %}

{% block content %}


<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-6 offset-2">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4"> Admin Login</h1>
                                </div>
                                <form class="user" method="post" novalidate>
                                    {% csrf_token %}

                                    {{ form.as_p }}
                                    <button class="btn btn-primary btn-user btn-block" type="submit">Login</button>
                                    {% if messages %}
                                    {% for message in messages %}
                                    {% if 'account' in message.message %}
                                    <p class="text-center text-danger">{{ message }}</p>
                                    {% endif %}
                                    {% endfor %}
                                    {% endif %}

                                </form>
                                <a  href="{% url 'authentication:admin_password_reset' %}"  class="mt-2" >Forget Password</a>

                            </div>

                        </div>
                    </div>
                </div>
            </div>


{% endblock %}

src/authentication/templates/frontend/authentication/admin_password_reset.html
{% extends 'frontend/base.html' %}

{% load static %}

{% block content %}

<div class="container p-5">
    <h2 class="font-weight-bold mt-3">Admin Reset Password</h2>
    <hr>
    <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Send email</button>
    </form>
</div>


<script src="{% static 'dist/js/app.js' %}"></script>
<script src="{% static 'dist/js/chunk-vendors.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js" crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>

{% if messages %}
{% for message in messages %}
{% if message.extra_tags == 'success' %}
<script>
    Toast.fire({
        title: '{{message}}',
        icon: 'success'
    });
</script>
{% elif message.extra_tags == 'error' %}
<script>
    Toast.fire({
        text: '{{message}}',
        icon: "error",
    });
</script>
{% endif %}
{% endfor %}
{% endif %}


{% endblock content %}

src/authentication/templates/frontend/authentication/login.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block meta_value %}
    <meta http-equiv="X-UA-Compatible" content="login">{% endblock %}
{% block title %}<title>Sign In</title>
    <link rel="icon" href="{% static '/assets/fav.png' %}" type="image/x-icon"/>{% endblock %}

{% block content %}
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center h-80vh">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="justify-content-center row">
                            <div class="col-12 col-sm-6">
                                <div class="p-4 p-sm-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome to Triple Choice</h1>
                                    </div>
                                    <form class="user" method="post" novalidate>
                                        {% csrf_token %}
                                        <input type="hidden" name="url" value="{{ url }}">
                                        <div class="mb-3">
                                            {{ form.username }}
                                            {% if messages %}
                                                {% for message in messages %}

                                                    {% if message.message == 'User not found' %}
                                                        <p class="text-center text-danger">{{ message }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <div class="mb-3">
                                            {{ form.password }}
                                            {% if messages %}
                                                {% for message in messages %}
                                                    {% if message.message == 'Credential not match' %}
                                                        <p class="text-center text-danger">{{ message }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <button class="btn btn-primary btn-user btn-block" type="submit">Sign in
                                        </button>
                                        {% if messages %}
                                            {% for message in messages %}
                                                {% if 'account' in message.message %}
                                                    <p class="text-center text-danger">{{ message }}</p>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}

                                    </form>
                                    <a href="{% url 'authentication:password_reset' %}" class="d-block mt-3 text-right">Forget
                                        Password?</a>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>


            </div>

        </div>

    </div>

    <script src="{% static 'dist/js/app.js' %}"></script>
    <script src="{% static 'dist/js/chunk-vendors.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js" crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>

    {% if messages %}
        {% for message in messages %}
            {% if message.extra_tags == 'success' %}
                <script>
                    Toast.fire({
                        title: '{{message}}',
                        icon: 'success'
                    });
                </script>
            {% elif message.extra_tags == 'error' %}
                <script>
                    Toast.fire({
                        text: '{{message}}',
                        icon: "error",
                    });
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock %}

src/authentication/templates/frontend/authentication/password_reset.html
{% extends 'frontend/base.html' %}

{% load static %}

{% block content %}

<div class="container p-5">
    <h2 class="font-weight-bold mt-3">Reset Password</h2>
    <hr>
    <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Send email</button>
    </form>
</div>


<script src="{% static 'dist/js/app.js' %}"></script>
<script src="{% static 'dist/js/chunk-vendors.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js" crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>

{% if messages %}
{% for message in messages %}
{% if message.extra_tags == 'success' %}
<script>
    Toast.fire({
        title: '{{message}}',
        icon: 'success'
    });
</script>
{% elif message.extra_tags == 'error' %}
<script>
    Toast.fire({
        text: '{{message}}',
        icon: "error",
    });
</script>
{% endif %}
{% endfor %}
{% endif %}


{% endblock content %}

src/authentication/templates/frontend/authentication/password_reset_complete.html
{% extends 'frontend/base.html' %}

{% load static %}

{% block content %}

  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="{% url 'authentication:login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

src/authentication/templates/frontend/authentication/password_reset_confirm.html
{% extends 'frontend/base.html' %}

{% load static %}

{% block content %}


  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock  %}
 

src/authentication/templates/frontend/authentication/password_reset_done.html
{% extends 'frontend/base.html' %}

{% load static %}

{% block content %}

<!--Password reset sent-->
<div class="container p-5">
    <h2 class="font-weight-bold mt-3">Password reset sent</h2>
    <hr>
    <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You
        should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you
        registered with, and check your spam folder.</p>
</div>


{% endblock content %}