src/authentication/urls.py
from django.urls import path, reverse_lazy

from authentication.views import CustomerLoginView, AuthCheckView, CustomerLogoutView, RegistrationView, activateView, \
    UserExists, ApiLoginView, PassWordResetView, AdminPassWordResetView, Profile

app_name = 'authentication'
urlpatterns = [
    path('sign-in/', CustomerLoginView.as_view(), name='login'),
    path('api/check-auth/', AuthCheckView.as_view(), name='auth_check'),
    path('logout/', CustomerLogoutView.as_view(), name='logout'),
    path('create-account/', RegistrationView.as_view(), name='register'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activateView,
         name='activate'),
    path('user/profile/', Profile.as_view(), name="user_profile"),
    path('user_exists/', UserExists.as_view(), name='user_exists'),

    path("api/api_login/", ApiLoginView.as_view(), name="api_login"),

    path("password_reset/", PassWordResetView.as_view(), name="password_reset"),
    path("admin_password_reset/", AdminPassWordResetView.as_view(), name="admin_password_reset"),

]

src/customer/urls.py
from django.urls import path, include

from customer.views import DashboardView, RequestsView, RequestDetailsView, RequestReviewView, RequestsHistoryView, \
    RequestHisoryDetailsView, OrdersView, OrdersHistoryView, OrdersHistoryDetailsView

from customer.api_views import CustomerRequestView, CustomerOrderView, RequestHistoryApiView, RequestReviewApiView, \
    RequestCancelView

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'api/customer-request', CustomerRequestView)
router.register(r'api/customer-order', CustomerOrderView)
router.register(r'api/customer-request-history', RequestHistoryApiView)
router.register(r'api/customer-request-review', RequestReviewApiView)

app_name = 'customer'

urlpatterns = [
    path('profile/', DashboardView.as_view(), name="customer_dashboard"),
    path('requests/', RequestsView.as_view(), name="customer_requests"),
    path('request-details/<str:order_id>', RequestDetailsView.as_view(), name="customer_request_details"),
    path('request/<int:request_id>/review', RequestReviewView.as_view(), name="request.review"),
    path('requests-history/<str:order_id>', RequestsHistoryView.as_view(), name="customer_requests_history"),
    path('request-history-details/<str:id>', RequestHisoryDetailsView.as_view(),
         name="customer_request_history_details"),

    path('orders/', OrdersView.as_view(), name='customer_orders'),
    path('order-history/<str:order_id>', OrdersHistoryView.as_view(), name='order_history'),
    path('order-history-details/<int:pk>', OrdersHistoryDetailsView.as_view(), name='order_history_details')
]

# api urls
urlpatterns += [
    path('', include(router.urls)),
    path('api/requests-cancel/<int:pk>', RequestCancelView.as_view())
]

src/page/urls.py
from django.urls import path

from page.views import page

urlpatterns = [
    path('<str:slug>/', page)
]

src/product/urls.py
from django.urls import path, include

from product.apis.product import AttributeList, ClassificationList, AttributeByClassification, PartApiView, \
    HomePageView, PartView, PartDetailsApiView, WizardView, AddPartSupplierView, DeletePartSupplierView, \
    PartDetailsByIdView
from product.apis.supplier import PartSupplierView
from product.apis.supplier import SupplierView

app_name = 'product'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('part/<slug:slug>/', PartView.as_view(), name="part.details"),
    path('part/supplier/<int:id>/', PartSupplierView.as_view(), name="part.supplier"),
    # TODO:form wizard
    path('wizard/<slug:slug>/', WizardView.as_view(), name="wizard"),
    path('add/part-supplier/', AddPartSupplierView.as_view(), name='add.part.supplier'),
    path('delete/part-supplier/<int:id>', DeletePartSupplierView.as_view(), name='delete.part.supplier')
]

# url for api
urlpatterns += [
    path('api/', include([
        path('attribute/', AttributeList.as_view()),
        path('classification/', ClassificationList.as_view()),
        path('attribute/<int:id>', AttributeByClassification.as_view()),
        path('part/', PartApiView.as_view()),
        path('part-update/<int:id>/', PartApiView.as_view()),
        path('part/<slug:slug>', PartDetailsApiView.as_view()),
        path('part/supplier/', SupplierView.as_view()),
        path('part-details/<str:id>/', PartDetailsByIdView.as_view())
    ]))
]

src/triple_choice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from triple_choice import settings
from django.contrib.auth import views as auth_views

admin.site.site_header = settings.APP_SITE_HEADER
admin.site.site_title = settings.APP_SITE_TITLE
admin.site.index_title = settings.APP_INDEX_TITLE

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('super-admin/', admin.site.urls),
    path('', include("product.urls")),
    path('', include("order.urls")),
    path('', include("authentication.urls")),
    path('', include("page.urls")),
    path('user/', include("customer.urls")),
    path('supplier/', include("supplier.urls")),
    # path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # path("v1/payment_intents", include("djstripe.urls", namespace="djstripe")),

    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="frontend/authentication/password_reset_done.html"),
         name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="frontend/authentication/password_reset_confirm.html", ),
         name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="frontend/authentication/password_reset_complete.html"),
         name="password_reset_complete")

]
urlpatterns + static(settings.STATIC_URL)
# urlpatterns += + static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/frontend/include/footer.html
<div class="footer d-flex align-items-center">
    <div class="container-fluid h-100">
        <div class="align-items-center d-flex flex-column flex-sm-row h-100 justify-content-between">
            <div class="menu-item">
                <div class="d-flex flex-column">
                    <div class="d-flex gap-3">
                        <a href="/">Home</a>
                        <a href="/about">About</a>
                        <a href="/contact">Contact</a>
                    </div>
                    <!--                    <p class="fw-600 text-primary m-0">Call or Text: <span class="text-secondary">833-883-0123</span></p>-->
                </div>
            </div>

            <div class="copyright mt-3 mt-sm-0 text-center">
                <p class="m-0">&copy; 2017 - 2018 TripleChoice. All Rights Reserved</p>
            </div>
        </div>
    </div>
</div>

src/templates/frontend/include/header.html
{% load static %}
<div class="container-fluid main-header">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center">
                {% if request.path != '/' %}
                    <a href="{% url 'product:home' %}" class="logo logo-350 mb-4">
                        <img class="img-fluid" src="{% static 'dist/img/main.png' %}" alt="">
                    </a>
                {% else %}
                    <p class="fw-600 text-primary fs-12 m-0">Call or Text: <span class="text-secondary nowrap"> {{ site.contact_number }} </span>
                    </p>
                {% endif %}
                <div class="d-flex">
                    {% if not user.is_authenticated %}
                        {% with request.resolver_match.url_name as url_name %}
                            {% if url_name != 'login' %}
                                <div class="nav-item">
                                    <a href="{% url 'authentication:login' %}"
                                       class="active bg-primary nav-link rounded text-light fs-12 custom-btn nowrap">Sign In</a>
                                </div>
                            {% endif %}
                            {% if url_name != "register" %}
                                <div class="nav-item">
                                    <a href="{% url 'authentication:register' %}"
                                       class="active bg-primary nav-link rounded text-light nowrap fs-12 custom-btn">Create
                                        an account</a>
                                </div>
                            {% endif %}
                        {% endwith %}
                    {% endif %}
                    {% if user.is_authenticated %}
                        <div class="nav-item">
                            <a class="nav-link bg-primary nav-link rounded text-light custom-btn"
                               href="{% url 'customer:customer_dashboard' %}">Dashboard</a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link bg-primary nav-link rounded text-light custom-btn"
                               href="{% url 'authentication:logout' %}">Logout</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>